# Generated by Django 5.0.6 on 2024-06-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumain',
            name='image',
            field=models.ImageField(upload_to='Menu/'),
        ),
    ]
