# Generated by Django 5.0.6 on 2024-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0003_menudrinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Menu/')),
                ('food_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('food_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
