# Generated by Django 5.0.6 on 2024-06-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0007_servicecustomers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCustomers',
        ),
    ]
