# Generated by Django 5.0.6 on 2024-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0008_delete_servicecustomers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Service/')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
    ]
